import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const url = process.env.DATABASE_URL;
if (!url) throw new Error("DATABASE_URL is not set");
const adapter = new PrismaPg({ connectionString: url });
const prisma = new PrismaClient({ adapter });

type HospitalInput = {
  name: string;
  type: "public" | "private" | "semi-government";
  city: string;
  province: string;
  address: string;
  area: string;
  lat: number;
  lng: number;
  phone: string;
  emergency: boolean;
  beds: number;
  rating: number;
  timings: string;
  established: number;
  specialties: { name: string; rating: number }[];
};

const hospitals: HospitalInput[] = [
  // ─── KARACHI ────────────────────────────────────────────────────────────────
  {
    name: "Aga Khan University Hospital",
    type: "private",
    city: "Karachi",
    province: "Sindh",
    address: "Stadium Road, Karachi",
    area: "Stadium Road",
    lat: 24.9012,
    lng: 67.0801,
    phone: "+92-21-34864000",
    emergency: true,
    beds: 700,
    rating: 4.9,
    timings: "24/7",
    established: 1985,
    specialties: [
      { name: "Cardiology", rating: 4.9 },
      { name: "Oncology", rating: 4.8 },
      { name: "Neurology", rating: 4.9 },
      { name: "Gynecology", rating: 4.8 },
      { name: "Orthopedics", rating: 4.7 },
      { name: "Gastroenterology", rating: 4.8 },
      { name: "Nephrology", rating: 4.8 },
      { name: "Transplant Surgery", rating: 4.9 },
    ],
  },
  {
    name: "Liaquat National Hospital",
    type: "private",
    city: "Karachi",
    province: "Sindh",
    address: "Stadium Road, Karachi",
    area: "Stadium Road",
    lat: 24.9003,
    lng: 67.0762,
    phone: "+92-21-34412000",
    emergency: true,
    beds: 850,
    rating: 4.5,
    timings: "24/7",
    established: 1958,
    specialties: [
      { name: "Cardiology", rating: 4.6 },
      { name: "General Surgery", rating: 4.5 },
      { name: "Neurology", rating: 4.4 },
      { name: "Orthopedics", rating: 4.5 },
      { name: "Gynecology", rating: 4.4 },
      { name: "Pediatrics", rating: 4.5 },
      { name: "Emergency Medicine", rating: 4.6 },
    ],
  },
  {
    name: "Civil Hospital Karachi",
    type: "public",
    city: "Karachi",
    province: "Sindh",
    address: "Sarfraz Raffiqui Road, Karachi",
    area: "Saddar",
    lat: 24.8566,
    lng: 67.0211,
    phone: "+92-21-99215740",
    emergency: true,
    beds: 1900,
    rating: 3.1,
    timings: "24/7",
    established: 1898,
    specialties: [
      { name: "Emergency Medicine", rating: 3.2 },
      { name: "General Surgery", rating: 3.1 },
      { name: "Gynecology", rating: 3.0 },
      { name: "Pediatrics", rating: 3.1 },
      { name: "Orthopedics", rating: 3.0 },
      { name: "Internal Medicine", rating: 3.2 },
    ],
  },
  {
    name: "South City Hospital",
    type: "private",
    city: "Karachi",
    province: "Sindh",
    address: "Block-2, Clifton, Karachi",
    area: "Clifton",
    lat: 24.8162,
    lng: 67.0301,
    phone: "+92-21-35292000",
    emergency: true,
    beds: 200,
    rating: 4.4,
    timings: "24/7",
    established: 2000,
    specialties: [
      { name: "Cardiology", rating: 4.5 },
      { name: "Cardiac Surgery", rating: 4.4 },
      { name: "Nephrology", rating: 4.3 },
      { name: "General Surgery", rating: 4.4 },
      { name: "Internal Medicine", rating: 4.3 },
    ],
  },
  {
    name: "Jinnah Postgraduate Medical Centre",
    type: "public",
    city: "Karachi",
    province: "Sindh",
    address: "Rafiqui H.J. Shaheed Road, Karachi",
    area: "Saddar",
    lat: 24.8687,
    lng: 67.0397,
    phone: "+92-21-99201300",
    emergency: true,
    beds: 1600,
    rating: 3.4,
    timings: "24/7",
    established: 1956,
    specialties: [
      { name: "Cardiology", rating: 3.5 },
      { name: "Neurology", rating: 3.4 },
      { name: "Burn Unit", rating: 3.6 },
      { name: "General Surgery", rating: 3.3 },
      { name: "Orthopedics", rating: 3.3 },
      { name: "Gynecology", rating: 3.4 },
    ],
  },
  {
    name: "Indus Hospital",
    type: "private",
    city: "Karachi",
    province: "Sindh",
    address: "Korangi Industrial Area, Karachi",
    area: "Korangi",
    lat: 24.8234,
    lng: 67.1283,
    phone: "+92-21-35112709",
    emergency: true,
    beds: 150,
    rating: 4.7,
    timings: "24/7",
    established: 2007,
    specialties: [
      { name: "Pediatrics", rating: 4.8 },
      { name: "Oncology", rating: 4.7 },
      { name: "Gynecology", rating: 4.7 },
      { name: "General Surgery", rating: 4.6 },
      { name: "Emergency Medicine", rating: 4.7 },
    ],
  },
  {
    name: "Ziauddin University Hospital",
    type: "private",
    city: "Karachi",
    province: "Sindh",
    address: "Block B, North Nazimabad, Karachi",
    area: "North Nazimabad",
    lat: 24.9348,
    lng: 67.0625,
    phone: "+92-21-36640600",
    emergency: true,
    beds: 400,
    rating: 4.3,
    timings: "24/7",
    established: 1995,
    specialties: [
      { name: "Neurosurgery", rating: 4.4 },
      { name: "Cardiology", rating: 4.3 },
      { name: "Orthopedics", rating: 4.3 },
      { name: "Gynecology", rating: 4.2 },
      { name: "General Surgery", rating: 4.3 },
      { name: "Psychiatry", rating: 4.2 },
    ],
  },
  {
    name: "Dow University Hospital",
    type: "public",
    city: "Karachi",
    province: "Sindh",
    address: "Mission Road, Karachi",
    area: "Saddar",
    lat: 24.8601,
    lng: 67.0271,
    phone: "+92-21-32614202",
    emergency: true,
    beds: 500,
    rating: 3.6,
    timings: "24/7",
    established: 2008,
    specialties: [
      { name: "General Surgery", rating: 3.7 },
      { name: "Gynecology", rating: 3.6 },
      { name: "Orthopedics", rating: 3.5 },
      { name: "Internal Medicine", rating: 3.7 },
      { name: "Ophthalmology", rating: 3.6 },
    ],
  },
  {
    name: "Patel Hospital Karachi",
    type: "private",
    city: "Karachi",
    province: "Sindh",
    address: "Opposite Jinnah Hospital, Garden, Karachi",
    area: "Garden",
    lat: 24.8631,
    lng: 67.0454,
    phone: "+92-21-32224677",
    emergency: false,
    beds: 100,
    rating: 4.1,
    timings: "8am–10pm",
    established: 1975,
    specialties: [
      { name: "Gastroenterology", rating: 4.2 },
      { name: "Internal Medicine", rating: 4.1 },
      { name: "Urology", rating: 4.0 },
      { name: "Nephrology", rating: 4.1 },
    ],
  },
  {
    name: "Abbasi Shaheed Hospital",
    type: "public",
    city: "Karachi",
    province: "Sindh",
    address: "M.A. Jinnah Road, Karachi",
    area: "Nazimabad",
    lat: 24.8953,
    lng: 67.0487,
    phone: "+92-21-36680260",
    emergency: true,
    beds: 800,
    rating: 3.2,
    timings: "24/7",
    established: 1978,
    specialties: [
      { name: "Emergency Medicine", rating: 3.3 },
      { name: "General Surgery", rating: 3.2 },
      { name: "Gynecology", rating: 3.1 },
      { name: "Pediatrics", rating: 3.2 },
      { name: "Orthopedics", rating: 3.1 },
    ],
  },
  {
    name: "National Medical Centre Karachi",
    type: "private",
    city: "Karachi",
    province: "Sindh",
    address: "M.A. Jinnah Road, Karachi",
    area: "Jinnah Road",
    lat: 24.8742,
    lng: 67.0398,
    phone: "+92-21-32724011",
    emergency: true,
    beds: 300,
    rating: 4.2,
    timings: "24/7",
    established: 1991,
    specialties: [
      { name: "Cardiology", rating: 4.3 },
      { name: "General Surgery", rating: 4.2 },
      { name: "Orthopedics", rating: 4.1 },
      { name: "Gynecology", rating: 4.2 },
      { name: "Neurology", rating: 4.1 },
    ],
  },
  {
    name: "Kidney Centre Karachi",
    type: "private",
    city: "Karachi",
    province: "Sindh",
    address: "Rafiqui Shaheed Road, Karachi",
    area: "Saddar",
    lat: 24.8699,
    lng: 67.0302,
    phone: "+92-21-99201700",
    emergency: false,
    beds: 100,
    rating: 4.6,
    timings: "8am–10pm",
    established: 1985,
    specialties: [
      { name: "Nephrology", rating: 4.7 },
      { name: "Transplant Surgery", rating: 4.6 },
      { name: "Urology", rating: 4.5 },
    ],
  },
  {
    name: "Karachi Institute of Heart Diseases",
    type: "public",
    city: "Karachi",
    province: "Sindh",
    address: "National Stadium Road, Karachi",
    area: "Gulshan-e-Iqbal",
    lat: 24.9201,
    lng: 67.0991,
    phone: "+92-21-99244441",
    emergency: true,
    beds: 300,
    rating: 4.1,
    timings: "24/7",
    established: 2001,
    specialties: [
      { name: "Cardiology", rating: 4.3 },
      { name: "Cardiac Surgery", rating: 4.1 },
      { name: "Vascular Surgery", rating: 4.0 },
    ],
  },
  {
    name: "Tabba Heart Institute",
    type: "private",
    city: "Karachi",
    province: "Sindh",
    address: "Karachi University Campus Road, Karachi",
    area: "Gulshan-e-Iqbal",
    lat: 24.9382,
    lng: 67.1011,
    phone: "+92-21-34132288",
    emergency: true,
    beds: 150,
    rating: 4.7,
    timings: "24/7",
    established: 2007,
    specialties: [
      { name: "Cardiology", rating: 4.8 },
      { name: "Cardiac Surgery", rating: 4.7 },
      { name: "Cardiac Rehabilitation", rating: 4.6 },
      { name: "Vascular Surgery", rating: 4.6 },
    ],
  },
  {
    name: "Sindh Institute of Urology & Transplantation",
    type: "public",
    city: "Karachi",
    province: "Sindh",
    address: "Chand Bibi Road, Karachi",
    area: "Saddar",
    lat: 24.8577,
    lng: 67.0231,
    phone: "+92-21-99215741",
    emergency: false,
    beds: 250,
    rating: 4.5,
    timings: "8am–8pm",
    established: 1981,
    specialties: [
      { name: "Nephrology", rating: 4.6 },
      { name: "Transplant Surgery", rating: 4.5 },
      { name: "Urology", rating: 4.5 },
    ],
  },
  {
    name: "Kiran Hospital Karachi",
    type: "public",
    city: "Karachi",
    province: "Sindh",
    address: "Block 16, Federal B Area, Karachi",
    area: "Federal B Area",
    lat: 24.9291,
    lng: 67.0652,
    phone: "+92-21-36979100",
    emergency: true,
    beds: 200,
    rating: 3.9,
    timings: "24/7",
    established: 2011,
    specialties: [
      { name: "Psychiatry", rating: 4.1 },
      { name: "Psychology", rating: 4.0 },
      { name: "Addiction Medicine", rating: 3.9 },
    ],
  },

  // ─── LAHORE ─────────────────────────────────────────────────────────────────
  {
    name: "Shaukat Khanum Memorial Cancer Hospital",
    type: "private",
    city: "Lahore",
    province: "Punjab",
    address: "7A Block R-3, M.A. Johar Town, Lahore",
    area: "Johar Town",
    lat: 31.4697,
    lng: 74.2728,
    phone: "+92-42-35945100",
    emergency: true,
    beds: 195,
    rating: 4.9,
    timings: "24/7",
    established: 1994,
    specialties: [
      { name: "Oncology", rating: 5.0 },
      { name: "Radiology", rating: 4.8 },
      { name: "General Surgery", rating: 4.7 },
      { name: "Pathology", rating: 4.9 },
      { name: "Palliative Care", rating: 4.8 },
    ],
  },
  {
    name: "Doctors Hospital & Medical Centre",
    type: "private",
    city: "Lahore",
    province: "Punjab",
    address: "152-G/1, Canal Bank, Johar Town, Lahore",
    area: "Johar Town",
    lat: 31.4721,
    lng: 74.2901,
    phone: "+92-42-35761999",
    emergency: true,
    beds: 300,
    rating: 4.7,
    timings: "24/7",
    established: 2000,
    specialties: [
      { name: "Cardiology", rating: 4.8 },
      { name: "Cardiac Surgery", rating: 4.7 },
      { name: "Neurosurgery", rating: 4.6 },
      { name: "Orthopedics", rating: 4.7 },
      { name: "Gynecology", rating: 4.6 },
      { name: "Gastroenterology", rating: 4.7 },
    ],
  },
  {
    name: "Services Hospital Lahore",
    type: "public",
    city: "Lahore",
    province: "Punjab",
    address: "Jail Road, Lahore",
    area: "Shadman",
    lat: 31.5477,
    lng: 74.3195,
    phone: "+92-42-99203337",
    emergency: true,
    beds: 1500,
    rating: 3.4,
    timings: "24/7",
    established: 1962,
    specialties: [
      { name: "Emergency Medicine", rating: 3.5 },
      { name: "General Surgery", rating: 3.4 },
      { name: "Orthopedics", rating: 3.3 },
      { name: "Gynecology", rating: 3.4 },
      { name: "Neurology", rating: 3.2 },
      { name: "Cardiology", rating: 3.5 },
    ],
  },
  {
    name: "Lahore General Hospital",
    type: "public",
    city: "Lahore",
    province: "Punjab",
    address: "Ferozpur Road, Lahore",
    area: "Ferozepur Road",
    lat: 31.5204,
    lng: 74.3587,
    phone: "+92-42-99231389",
    emergency: true,
    beds: 1200,
    rating: 3.2,
    timings: "24/7",
    established: 1970,
    specialties: [
      { name: "General Surgery", rating: 3.3 },
      { name: "Gynecology", rating: 3.2 },
      { name: "Pediatrics", rating: 3.1 },
      { name: "Internal Medicine", rating: 3.3 },
      { name: "Orthopedics", rating: 3.1 },
    ],
  },
  {
    name: "Sir Ganga Ram Hospital",
    type: "public",
    city: "Lahore",
    province: "Punjab",
    address: "Queens Road, Lahore",
    area: "Queens Road",
    lat: 31.5601,
    lng: 74.3312,
    phone: "+92-42-99200581",
    emergency: true,
    beds: 900,
    rating: 3.5,
    timings: "24/7",
    established: 1921,
    specialties: [
      { name: "Cardiology", rating: 3.6 },
      { name: "Neurology", rating: 3.5 },
      { name: "General Surgery", rating: 3.5 },
      { name: "Gynecology", rating: 3.4 },
      { name: "Orthopedics", rating: 3.4 },
    ],
  },
  {
    name: "Mayo Hospital Lahore",
    type: "public",
    city: "Lahore",
    province: "Punjab",
    address: "The Mall, Lahore",
    area: "The Mall",
    lat: 31.5688,
    lng: 74.3221,
    phone: "+92-42-99200600",
    emergency: true,
    beds: 2000,
    rating: 3.3,
    timings: "24/7",
    established: 1871,
    specialties: [
      { name: "Emergency Medicine", rating: 3.4 },
      { name: "General Surgery", rating: 3.3 },
      { name: "Orthopedics", rating: 3.2 },
      { name: "Neurology", rating: 3.3 },
      { name: "Gynecology", rating: 3.2 },
      { name: "Dermatology", rating: 3.4 },
    ],
  },
  {
    name: "Ittefaq Hospital",
    type: "private",
    city: "Lahore",
    province: "Punjab",
    address: "19 Jail Road, Model Town, Lahore",
    area: "Model Town",
    lat: 31.4849,
    lng: 74.3201,
    phone: "+92-42-35761100",
    emergency: true,
    beds: 350,
    rating: 4.5,
    timings: "24/7",
    established: 1998,
    specialties: [
      { name: "Cardiology", rating: 4.6 },
      { name: "Cardiac Surgery", rating: 4.5 },
      { name: "Orthopedics", rating: 4.5 },
      { name: "Gynecology", rating: 4.4 },
      { name: "Urology", rating: 4.4 },
      { name: "Gastroenterology", rating: 4.5 },
    ],
  },
  {
    name: "Hameed Latif Hospital",
    type: "private",
    city: "Lahore",
    province: "Punjab",
    address: "4 Abu Bakar Block, Garden Town, Lahore",
    area: "Garden Town",
    lat: 31.4971,
    lng: 74.3302,
    phone: "+92-42-35761280",
    emergency: true,
    beds: 250,
    rating: 4.4,
    timings: "24/7",
    established: 1985,
    specialties: [
      { name: "Cardiology", rating: 4.5 },
      { name: "General Surgery", rating: 4.4 },
      { name: "Gynecology", rating: 4.5 },
      { name: "Pediatrics", rating: 4.3 },
      { name: "Nephrology", rating: 4.3 },
    ],
  },
  {
    name: "National Hospital & Medical Centre Lahore",
    type: "private",
    city: "Lahore",
    province: "Punjab",
    address: "132/3, L-Block, DHA Phase 1, Lahore",
    area: "DHA",
    lat: 31.4785,
    lng: 74.4088,
    phone: "+92-42-35693988",
    emergency: true,
    beds: 180,
    rating: 4.3,
    timings: "24/7",
    established: 1997,
    specialties: [
      { name: "Cardiology", rating: 4.4 },
      { name: "Orthopedics", rating: 4.3 },
      { name: "Gynecology", rating: 4.3 },
      { name: "Neurosurgery", rating: 4.2 },
      { name: "General Surgery", rating: 4.3 },
    ],
  },
  {
    name: "Surgimed Hospital",
    type: "private",
    city: "Lahore",
    province: "Punjab",
    address: "1 Zafar Ali Road, Gulberg V, Lahore",
    area: "Gulberg",
    lat: 31.5089,
    lng: 74.3489,
    phone: "+92-42-35776771",
    emergency: false,
    beds: 150,
    rating: 4.3,
    timings: "8am–11pm",
    established: 1994,
    specialties: [
      { name: "General Surgery", rating: 4.4 },
      { name: "Plastic Surgery", rating: 4.3 },
      { name: "Urology", rating: 4.2 },
      { name: "Gynecology", rating: 4.3 },
    ],
  },
  {
    name: "Bahria International Hospital Lahore",
    type: "private",
    city: "Lahore",
    province: "Punjab",
    address: "Takbeer Block, Sector B, Bahria Town, Lahore",
    area: "Bahria Town",
    lat: 31.3664,
    lng: 74.1831,
    phone: "+92-42-35879000",
    emergency: true,
    beds: 300,
    rating: 4.4,
    timings: "24/7",
    established: 2012,
    specialties: [
      { name: "Cardiology", rating: 4.5 },
      { name: "Orthopedics", rating: 4.4 },
      { name: "Gynecology", rating: 4.4 },
      { name: "Neurosurgery", rating: 4.3 },
      { name: "General Surgery", rating: 4.4 },
      { name: "Gastroenterology", rating: 4.3 },
    ],
  },
  {
    name: "Shalamar Hospital Lahore",
    type: "semi-government",
    city: "Lahore",
    province: "Punjab",
    address: "Shalimar Link Road, Lahore",
    area: "Shalimar",
    lat: 31.5799,
    lng: 74.3811,
    phone: "+92-42-37490000",
    emergency: true,
    beds: 800,
    rating: 3.8,
    timings: "24/7",
    established: 1985,
    specialties: [
      { name: "Cardiology", rating: 3.9 },
      { name: "General Surgery", rating: 3.8 },
      { name: "Gynecology", rating: 3.8 },
      { name: "Orthopedics", rating: 3.7 },
      { name: "Neurology", rating: 3.7 },
      { name: "Pediatrics", rating: 3.8 },
    ],
  },
  {
    name: "Punjab Institute of Cardiology",
    type: "public",
    city: "Lahore",
    province: "Punjab",
    address: "Davis Road, Lahore",
    area: "Davis Road",
    lat: 31.5498,
    lng: 74.3289,
    phone: "+92-42-99203051",
    emergency: true,
    beds: 600,
    rating: 4.1,
    timings: "24/7",
    established: 1997,
    specialties: [
      { name: "Cardiology", rating: 4.3 },
      { name: "Cardiac Surgery", rating: 4.1 },
      { name: "Vascular Surgery", rating: 4.0 },
      { name: "Cardiac Rehabilitation", rating: 4.0 },
    ],
  },
  {
    name: "Jinnah Hospital Lahore",
    type: "public",
    city: "Lahore",
    province: "Punjab",
    address: "Allama Shabbir Ahmed Usmani Road, Lahore",
    area: "Ferozepur Road",
    lat: 31.5241,
    lng: 74.3411,
    phone: "+92-42-99231300",
    emergency: true,
    beds: 1400,
    rating: 3.3,
    timings: "24/7",
    established: 1956,
    specialties: [
      { name: "Emergency Medicine", rating: 3.4 },
      { name: "General Surgery", rating: 3.3 },
      { name: "Gynecology", rating: 3.3 },
      { name: "Orthopedics", rating: 3.2 },
      { name: "Oncology", rating: 3.3 },
      { name: "Nephrology", rating: 3.2 },
    ],
  },
  {
    name: "The Children's Hospital Lahore",
    type: "public",
    city: "Lahore",
    province: "Punjab",
    address: "Ferozepur Road, Lahore",
    area: "Ferozepur Road",
    lat: 31.5108,
    lng: 74.3479,
    phone: "+92-42-99231400",
    emergency: true,
    beds: 700,
    rating: 4.0,
    timings: "24/7",
    established: 2006,
    specialties: [
      { name: "Pediatrics", rating: 4.1 },
      { name: "Pediatric Surgery", rating: 4.0 },
      { name: "Neonatology", rating: 4.0 },
      { name: "Pediatric Cardiology", rating: 3.9 },
      { name: "Pediatric Oncology", rating: 3.9 },
    ],
  },
  {
    name: "Lahore Heart Institute",
    type: "private",
    city: "Lahore",
    province: "Punjab",
    address: "Wahdat Colony, Lahore",
    area: "Wahdat Colony",
    lat: 31.4911,
    lng: 74.3881,
    phone: "+92-42-35291001",
    emergency: true,
    beds: 120,
    rating: 4.4,
    timings: "24/7",
    established: 2004,
    specialties: [
      { name: "Cardiology", rating: 4.5 },
      { name: "Cardiac Surgery", rating: 4.4 },
      { name: "Vascular Surgery", rating: 4.3 },
    ],
  },
  {
    name: "Farooq Hospital Lahore",
    type: "private",
    city: "Lahore",
    province: "Punjab",
    address: "West Wood Colony, Lahore",
    area: "Westwood",
    lat: 31.4488,
    lng: 74.2671,
    phone: "+92-42-35220222",
    emergency: true,
    beds: 200,
    rating: 4.2,
    timings: "24/7",
    established: 2002,
    specialties: [
      { name: "General Surgery", rating: 4.3 },
      { name: "Gynecology", rating: 4.3 },
      { name: "Orthopedics", rating: 4.1 },
      { name: "Emergency Medicine", rating: 4.2 },
    ],
  },

  // ─── ISLAMABAD ───────────────────────────────────────────────────────────────
  {
    name: "Pakistan Institute of Medical Sciences (PIMS)",
    type: "public",
    city: "Islamabad",
    province: "ICT",
    address: "G-8/3, Islamabad",
    area: "G-8",
    lat: 33.6844,
    lng: 73.0479,
    phone: "+92-51-9261170",
    emergency: true,
    beds: 1500,
    rating: 3.6,
    timings: "24/7",
    established: 1983,
    specialties: [
      { name: "Cardiology", rating: 3.7 },
      { name: "Neurosurgery", rating: 3.6 },
      { name: "Orthopedics", rating: 3.5 },
      { name: "Gynecology", rating: 3.6 },
      { name: "Pediatrics", rating: 3.7 },
      { name: "Oncology", rating: 3.5 },
      { name: "Transplant Surgery", rating: 3.7 },
    ],
  },
  {
    name: "Shifa International Hospital",
    type: "private",
    city: "Islamabad",
    province: "ICT",
    address: "Sector H-8/4, Islamabad",
    area: "H-8",
    lat: 33.6609,
    lng: 73.0552,
    phone: "+92-51-8464646",
    emergency: true,
    beds: 500,
    rating: 4.7,
    timings: "24/7",
    established: 1987,
    specialties: [
      { name: "Cardiology", rating: 4.8 },
      { name: "Cardiac Surgery", rating: 4.7 },
      { name: "Neurology", rating: 4.7 },
      { name: "Orthopedics", rating: 4.6 },
      { name: "Gynecology", rating: 4.7 },
      { name: "Oncology", rating: 4.6 },
      { name: "Transplant Surgery", rating: 4.7 },
    ],
  },
  {
    name: "Kulsum International Hospital",
    type: "private",
    city: "Islamabad",
    province: "ICT",
    address: "60-W, Jinnah Avenue, Blue Area, Islamabad",
    area: "Blue Area",
    lat: 33.7215,
    lng: 73.0898,
    phone: "+92-51-2803444",
    emergency: true,
    beds: 200,
    rating: 4.4,
    timings: "24/7",
    established: 1999,
    specialties: [
      { name: "Gynecology", rating: 4.5 },
      { name: "Pediatrics", rating: 4.4 },
      { name: "General Surgery", rating: 4.3 },
      { name: "Cardiology", rating: 4.3 },
    ],
  },
  {
    name: "Maroof International Hospital",
    type: "private",
    city: "Islamabad",
    province: "ICT",
    address: "Sector H-8, Islamabad",
    area: "H-8",
    lat: 33.6701,
    lng: 73.0487,
    phone: "+92-51-8444001",
    emergency: true,
    beds: 250,
    rating: 4.5,
    timings: "24/7",
    established: 2010,
    specialties: [
      { name: "Orthopedics", rating: 4.6 },
      { name: "Neurosurgery", rating: 4.5 },
      { name: "General Surgery", rating: 4.5 },
      { name: "Gynecology", rating: 4.4 },
      { name: "Cardiology", rating: 4.4 },
    ],
  },
  {
    name: "Capital Hospital Islamabad",
    type: "public",
    city: "Islamabad",
    province: "ICT",
    address: "G-7/1, Islamabad",
    area: "G-7",
    lat: 33.7101,
    lng: 73.0781,
    phone: "+92-51-9211580",
    emergency: true,
    beds: 500,
    rating: 3.5,
    timings: "24/7",
    established: 1992,
    specialties: [
      { name: "General Surgery", rating: 3.6 },
      { name: "Gynecology", rating: 3.5 },
      { name: "Orthopedics", rating: 3.4 },
      { name: "Internal Medicine", rating: 3.6 },
    ],
  },
  {
    name: "Poly Clinic Hospital Islamabad",
    type: "public",
    city: "Islamabad",
    province: "ICT",
    address: "G-6/2, Islamabad",
    area: "G-6",
    lat: 33.7239,
    lng: 73.0952,
    phone: "+92-51-9205210",
    emergency: true,
    beds: 700,
    rating: 3.4,
    timings: "24/7",
    established: 1969,
    specialties: [
      { name: "Emergency Medicine", rating: 3.5 },
      { name: "General Surgery", rating: 3.4 },
      { name: "Gynecology", rating: 3.4 },
      { name: "Orthopedics", rating: 3.3 },
      { name: "Cardiology", rating: 3.4 },
    ],
  },
  {
    name: "Ali Medical Centre Islamabad",
    type: "private",
    city: "Islamabad",
    province: "ICT",
    address: "F-8 Markaz, Islamabad",
    area: "F-8",
    lat: 33.7081,
    lng: 73.0462,
    phone: "+92-51-2851000",
    emergency: true,
    beds: 180,
    rating: 4.3,
    timings: "24/7",
    established: 2007,
    specialties: [
      { name: "Cardiology", rating: 4.4 },
      { name: "General Surgery", rating: 4.3 },
      { name: "Gynecology", rating: 4.3 },
      { name: "Orthopedics", rating: 4.2 },
      { name: "Neurology", rating: 4.2 },
    ],
  },

  // ─── RAWALPINDI ───────────────────────────────────────────────────────────────
  {
    name: "Holy Family Hospital Rawalpindi",
    type: "public",
    city: "Rawalpindi",
    province: "Punjab",
    address: "Satellite Town, Rawalpindi",
    area: "Satellite Town",
    lat: 33.6101,
    lng: 73.0877,
    phone: "+92-51-9290301",
    emergency: true,
    beds: 900,
    rating: 3.5,
    timings: "24/7",
    established: 1948,
    specialties: [
      { name: "Gynecology", rating: 3.6 },
      { name: "Pediatrics", rating: 3.5 },
      { name: "General Surgery", rating: 3.4 },
      { name: "Orthopedics", rating: 3.4 },
      { name: "Internal Medicine", rating: 3.5 },
    ],
  },
  {
    name: "Benazir Bhutto Hospital Rawalpindi",
    type: "public",
    city: "Rawalpindi",
    province: "Punjab",
    address: "Murree Road, Rawalpindi",
    area: "Murree Road",
    lat: 33.5651,
    lng: 73.1093,
    phone: "+92-51-9290321",
    emergency: true,
    beds: 1200,
    rating: 3.3,
    timings: "24/7",
    established: 1955,
    specialties: [
      { name: "Emergency Medicine", rating: 3.4 },
      { name: "General Surgery", rating: 3.3 },
      { name: "Gynecology", rating: 3.3 },
      { name: "Orthopedics", rating: 3.2 },
      { name: "Cardiology", rating: 3.3 },
    ],
  },
  {
    name: "CMH Rawalpindi",
    type: "semi-government",
    city: "Rawalpindi",
    province: "Punjab",
    address: "The Mall, Rawalpindi Cantonment",
    area: "Rawalpindi Cantonment",
    lat: 33.5974,
    lng: 73.0683,
    phone: "+92-51-9270341",
    emergency: true,
    beds: 1100,
    rating: 4.2,
    timings: "24/7",
    established: 1947,
    specialties: [
      { name: "Cardiology", rating: 4.3 },
      { name: "Neurosurgery", rating: 4.2 },
      { name: "Orthopedics", rating: 4.3 },
      { name: "General Surgery", rating: 4.2 },
      { name: "Gynecology", rating: 4.1 },
    ],
  },

  // ─── PESHAWAR ────────────────────────────────────────────────────────────────
  {
    name: "Lady Reading Hospital Peshawar",
    type: "public",
    city: "Peshawar",
    province: "KPK",
    address: "Peshawar Road, Peshawar",
    area: "Saddar",
    lat: 34.0151,
    lng: 71.5249,
    phone: "+92-91-9211290",
    emergency: true,
    beds: 1800,
    rating: 3.5,
    timings: "24/7",
    established: 1927,
    specialties: [
      { name: "Emergency Medicine", rating: 3.6 },
      { name: "General Surgery", rating: 3.5 },
      { name: "Gynecology", rating: 3.5 },
      { name: "Orthopedics", rating: 3.4 },
      { name: "Neurosurgery", rating: 3.5 },
      { name: "Cardiology", rating: 3.4 },
      { name: "Pediatrics", rating: 3.5 },
    ],
  },
  {
    name: "Khyber Teaching Hospital",
    type: "public",
    city: "Peshawar",
    province: "KPK",
    address: "Peshawar Road, Peshawar",
    area: "Hayatabad",
    lat: 34.0021,
    lng: 71.4818,
    phone: "+92-91-9217121",
    emergency: true,
    beds: 1200,
    rating: 3.4,
    timings: "24/7",
    established: 1979,
    specialties: [
      { name: "General Surgery", rating: 3.4 },
      { name: "Orthopedics", rating: 3.3 },
      { name: "Gynecology", rating: 3.4 },
      { name: "Pediatrics", rating: 3.4 },
      { name: "Cardiology", rating: 3.3 },
    ],
  },
  {
    name: "Hayatabad Medical Complex",
    type: "public",
    city: "Peshawar",
    province: "KPK",
    address: "Phase-5, Hayatabad, Peshawar",
    area: "Hayatabad",
    lat: 33.9988,
    lng: 71.4649,
    phone: "+92-91-9217600",
    emergency: true,
    beds: 1000,
    rating: 3.6,
    timings: "24/7",
    established: 1987,
    specialties: [
      { name: "Cardiology", rating: 3.7 },
      { name: "Neurosurgery", rating: 3.6 },
      { name: "Orthopedics", rating: 3.5 },
      { name: "Gynecology", rating: 3.6 },
      { name: "Burn Unit", rating: 3.7 },
      { name: "Nephrology", rating: 3.5 },
    ],
  },
  {
    name: "Northwest General Hospital",
    type: "private",
    city: "Peshawar",
    province: "KPK",
    address: "Phase 5, Hayatabad, Peshawar",
    area: "Hayatabad",
    lat: 34.0011,
    lng: 71.4702,
    phone: "+92-91-5892001",
    emergency: true,
    beds: 250,
    rating: 4.3,
    timings: "24/7",
    established: 2005,
    specialties: [
      { name: "Cardiology", rating: 4.4 },
      { name: "Orthopedics", rating: 4.3 },
      { name: "General Surgery", rating: 4.3 },
      { name: "Gynecology", rating: 4.2 },
      { name: "Neurosurgery", rating: 4.2 },
    ],
  },
  {
    name: "Rehman Medical Institute",
    type: "private",
    city: "Peshawar",
    province: "KPK",
    address: "Phase 5, Hayatabad, Peshawar",
    area: "Hayatabad",
    lat: 34.0039,
    lng: 71.4745,
    phone: "+92-91-5840050",
    emergency: true,
    beds: 300,
    rating: 4.5,
    timings: "24/7",
    established: 2010,
    specialties: [
      { name: "Cardiology", rating: 4.6 },
      { name: "Cardiac Surgery", rating: 4.5 },
      { name: "Neurology", rating: 4.5 },
      { name: "Orthopedics", rating: 4.5 },
      { name: "Gynecology", rating: 4.4 },
      { name: "Oncology", rating: 4.4 },
    ],
  },

  // ─── QUETTA ─────────────────────────────────────────────────────────────────
  {
    name: "Bolan Medical Complex Quetta",
    type: "public",
    city: "Quetta",
    province: "Balochistan",
    address: "Brewery Road, Quetta",
    area: "Brewery Road",
    lat: 30.2089,
    lng: 67.0104,
    phone: "+92-81-9201640",
    emergency: true,
    beds: 1000,
    rating: 3.0,
    timings: "24/7",
    established: 1972,
    specialties: [
      { name: "Emergency Medicine", rating: 3.1 },
      { name: "General Surgery", rating: 3.0 },
      { name: "Gynecology", rating: 3.0 },
      { name: "Orthopedics", rating: 2.9 },
      { name: "Pediatrics", rating: 3.0 },
    ],
  },
  {
    name: "Sandeman Provincial Hospital",
    type: "public",
    city: "Quetta",
    province: "Balochistan",
    address: "Mission Road, Quetta",
    area: "Mission Road",
    lat: 30.1951,
    lng: 66.9931,
    phone: "+92-81-9202034",
    emergency: true,
    beds: 800,
    rating: 2.9,
    timings: "24/7",
    established: 1900,
    specialties: [
      { name: "General Surgery", rating: 3.0 },
      { name: "Gynecology", rating: 2.9 },
      { name: "Pediatrics", rating: 2.9 },
      { name: "Internal Medicine", rating: 3.0 },
    ],
  },
  {
    name: "Quetta Institute of Medical Sciences",
    type: "private",
    city: "Quetta",
    province: "Balochistan",
    address: "Airport Road, Quetta",
    area: "Airport Road",
    lat: 30.2321,
    lng: 66.9521,
    phone: "+92-81-2820001",
    emergency: true,
    beds: 200,
    rating: 4.0,
    timings: "24/7",
    established: 2012,
    specialties: [
      { name: "Cardiology", rating: 4.1 },
      { name: "General Surgery", rating: 4.0 },
      { name: "Gynecology", rating: 4.0 },
      { name: "Orthopedics", rating: 3.9 },
      { name: "Internal Medicine", rating: 4.0 },
    ],
  },

  // ─── MULTAN ──────────────────────────────────────────────────────────────────
  {
    name: "Nishtar Hospital Multan",
    type: "public",
    city: "Multan",
    province: "Punjab",
    address: "Nishtar Road, Multan",
    area: "Nishtar Road",
    lat: 30.1945,
    lng: 71.4686,
    phone: "+92-61-9200450",
    emergency: true,
    beds: 1700,
    rating: 3.4,
    timings: "24/7",
    established: 1953,
    specialties: [
      { name: "Cardiology", rating: 3.5 },
      { name: "General Surgery", rating: 3.4 },
      { name: "Gynecology", rating: 3.4 },
      { name: "Orthopedics", rating: 3.3 },
      { name: "Neurology", rating: 3.3 },
      { name: "Pediatrics", rating: 3.4 },
    ],
  },
  {
    name: "Multan Institute of Kidney Diseases",
    type: "public",
    city: "Multan",
    province: "Punjab",
    address: "Opposite Nishtar Hospital, Multan",
    area: "Nishtar Road",
    lat: 30.1978,
    lng: 71.4711,
    phone: "+92-61-9200620",
    emergency: false,
    beds: 150,
    rating: 4.0,
    timings: "8am–10pm",
    established: 2004,
    specialties: [
      { name: "Nephrology", rating: 4.2 },
      { name: "Urology", rating: 4.0 },
      { name: "Transplant Surgery", rating: 4.1 },
    ],
  },
  {
    name: "Children Hospital Multan",
    type: "public",
    city: "Multan",
    province: "Punjab",
    address: "Nishtar Road, Multan",
    area: "Nishtar Road",
    lat: 30.1921,
    lng: 71.4699,
    phone: "+92-61-9200500",
    emergency: true,
    beds: 500,
    rating: 3.6,
    timings: "24/7",
    established: 1980,
    specialties: [
      { name: "Pediatrics", rating: 3.7 },
      { name: "Pediatric Surgery", rating: 3.6 },
      { name: "Neonatology", rating: 3.6 },
      { name: "Pediatric Cardiology", rating: 3.5 },
    ],
  },
  {
    name: "Bakhtawar Amin Medical College Hospital",
    type: "semi-government",
    city: "Multan",
    province: "Punjab",
    address: "Multan-Lahore Road, Multan",
    area: "Multan Road",
    lat: 30.2201,
    lng: 71.5012,
    phone: "+92-61-6511786",
    emergency: true,
    beds: 400,
    rating: 3.8,
    timings: "24/7",
    established: 1995,
    specialties: [
      { name: "General Surgery", rating: 3.9 },
      { name: "Gynecology", rating: 3.8 },
      { name: "Orthopedics", rating: 3.7 },
      { name: "Cardiology", rating: 3.8 },
      { name: "Pediatrics", rating: 3.8 },
    ],
  },

  // ─── FAISALABAD ─────────────────────────────────────────────────────────────
  {
    name: "Allied Hospital Faisalabad",
    type: "public",
    city: "Faisalabad",
    province: "Punjab",
    address: "Jail Road, Faisalabad",
    area: "Jail Road",
    lat: 31.4181,
    lng: 73.0791,
    phone: "+92-41-9200451",
    emergency: true,
    beds: 1500,
    rating: 3.3,
    timings: "24/7",
    established: 1974,
    specialties: [
      { name: "Emergency Medicine", rating: 3.4 },
      { name: "General Surgery", rating: 3.3 },
      { name: "Gynecology", rating: 3.3 },
      { name: "Orthopedics", rating: 3.2 },
      { name: "Cardiology", rating: 3.3 },
      { name: "Pediatrics", rating: 3.3 },
    ],
  },
  {
    name: "Faisalabad Institute of Cardiology",
    type: "public",
    city: "Faisalabad",
    province: "Punjab",
    address: "Jail Road, Faisalabad",
    area: "Jail Road",
    lat: 31.4199,
    lng: 73.0782,
    phone: "+92-41-9200478",
    emergency: true,
    beds: 300,
    rating: 4.0,
    timings: "24/7",
    established: 2001,
    specialties: [
      { name: "Cardiology", rating: 4.2 },
      { name: "Cardiac Surgery", rating: 4.0 },
      { name: "Vascular Surgery", rating: 3.9 },
    ],
  },
  {
    name: "National Hospital Faisalabad",
    type: "private",
    city: "Faisalabad",
    province: "Punjab",
    address: "Susan Road, Madina Town, Faisalabad",
    area: "Madina Town",
    lat: 31.4551,
    lng: 73.1201,
    phone: "+92-41-8732501",
    emergency: true,
    beds: 200,
    rating: 4.2,
    timings: "24/7",
    established: 2006,
    specialties: [
      { name: "Cardiology", rating: 4.3 },
      { name: "General Surgery", rating: 4.2 },
      { name: "Gynecology", rating: 4.2 },
      { name: "Orthopedics", rating: 4.1 },
      { name: "Neurology", rating: 4.1 },
    ],
  },
  {
    name: "DHQ Hospital Faisalabad",
    type: "public",
    city: "Faisalabad",
    province: "Punjab",
    address: "Kotwali Road, Faisalabad",
    area: "Kotwali Road",
    lat: 31.4189,
    lng: 73.0941,
    phone: "+92-41-9200250",
    emergency: true,
    beds: 800,
    rating: 3.1,
    timings: "24/7",
    established: 1968,
    specialties: [
      { name: "General Surgery", rating: 3.2 },
      { name: "Gynecology", rating: 3.1 },
      { name: "Internal Medicine", rating: 3.2 },
      { name: "Pediatrics", rating: 3.1 },
    ],
  },

  // ─── HYDERABAD ───────────────────────────────────────────────────────────────
  {
    name: "Liaquat University Hospital Hyderabad",
    type: "public",
    city: "Hyderabad",
    province: "Sindh",
    address: "Jamshoro, Hyderabad",
    area: "Jamshoro",
    lat: 25.4394,
    lng: 68.3782,
    phone: "+92-22-9213021",
    emergency: true,
    beds: 1400,
    rating: 3.2,
    timings: "24/7",
    established: 1976,
    specialties: [
      { name: "Emergency Medicine", rating: 3.3 },
      { name: "General Surgery", rating: 3.2 },
      { name: "Gynecology", rating: 3.2 },
      { name: "Pediatrics", rating: 3.1 },
      { name: "Orthopedics", rating: 3.1 },
    ],
  },
  {
    name: "Civil Hospital Hyderabad",
    type: "public",
    city: "Hyderabad",
    province: "Sindh",
    address: "Court Road, Hyderabad",
    area: "Court Road",
    lat: 25.3648,
    lng: 68.3651,
    phone: "+92-22-9200401",
    emergency: true,
    beds: 900,
    rating: 2.9,
    timings: "24/7",
    established: 1945,
    specialties: [
      { name: "General Surgery", rating: 3.0 },
      { name: "Gynecology", rating: 2.9 },
      { name: "Pediatrics", rating: 2.9 },
      { name: "Internal Medicine", rating: 3.0 },
    ],
  },
  {
    name: "Isra University Hospital",
    type: "private",
    city: "Hyderabad",
    province: "Sindh",
    address: "Hala Naka, Hyderabad",
    area: "Hala Naka",
    lat: 25.3801,
    lng: 68.3401,
    phone: "+92-22-2030001",
    emergency: true,
    beds: 300,
    rating: 4.0,
    timings: "24/7",
    established: 1998,
    specialties: [
      { name: "Ophthalmology", rating: 4.2 },
      { name: "Cardiology", rating: 4.0 },
      { name: "General Surgery", rating: 4.0 },
      { name: "Gynecology", rating: 3.9 },
      { name: "Orthopedics", rating: 3.9 },
    ],
  },
  {
    name: "Aga Khan Hospital Hyderabad",
    type: "private",
    city: "Hyderabad",
    province: "Sindh",
    address: "Saddar, Hyderabad",
    area: "Saddar",
    lat: 25.3674,
    lng: 68.3601,
    phone: "+92-22-2780101",
    emergency: true,
    beds: 120,
    rating: 4.3,
    timings: "24/7",
    established: 2000,
    specialties: [
      { name: "General Surgery", rating: 4.3 },
      { name: "Gynecology", rating: 4.3 },
      { name: "Pediatrics", rating: 4.2 },
      { name: "Internal Medicine", rating: 4.2 },
    ],
  },

  // ─── SUKKUR ──────────────────────────────────────────────────────────────────
  {
    name: "Ghulam Muhammad Mahar Medical College Hospital",
    type: "public",
    city: "Sukkur",
    province: "Sindh",
    address: "Sukkur Bypass, Sukkur",
    area: "Sukkur Bypass",
    lat: 27.7052,
    lng: 68.8573,
    phone: "+92-71-5630201",
    emergency: true,
    beds: 600,
    rating: 3.1,
    timings: "24/7",
    established: 1990,
    specialties: [
      { name: "General Surgery", rating: 3.2 },
      { name: "Gynecology", rating: 3.1 },
      { name: "Pediatrics", rating: 3.1 },
      { name: "Internal Medicine", rating: 3.2 },
    ],
  },
  {
    name: "Civil Hospital Sukkur",
    type: "public",
    city: "Sukkur",
    province: "Sindh",
    address: "Military Road, Sukkur",
    area: "Military Road",
    lat: 27.7052,
    lng: 68.8401,
    phone: "+92-71-5620401",
    emergency: true,
    beds: 400,
    rating: 2.8,
    timings: "24/7",
    established: 1940,
    specialties: [
      { name: "Emergency Medicine", rating: 2.9 },
      { name: "General Surgery", rating: 2.8 },
      { name: "Gynecology", rating: 2.8 },
    ],
  },

  // ─── BAHAWALPUR ───────────────────────────────────────────────────────────────
  {
    name: "Bahawal Victoria Hospital",
    type: "public",
    city: "Bahawalpur",
    province: "Punjab",
    address: "Circular Road, Bahawalpur",
    area: "Circular Road",
    lat: 29.3976,
    lng: 71.6866,
    phone: "+92-62-9255240",
    emergency: true,
    beds: 1200,
    rating: 3.2,
    timings: "24/7",
    established: 1906,
    specialties: [
      { name: "Emergency Medicine", rating: 3.3 },
      { name: "General Surgery", rating: 3.2 },
      { name: "Gynecology", rating: 3.2 },
      { name: "Orthopedics", rating: 3.1 },
      { name: "Pediatrics", rating: 3.2 },
    ],
  },
  {
    name: "Quaid-e-Azam Medical College Hospital",
    type: "public",
    city: "Bahawalpur",
    province: "Punjab",
    address: "Bahawalpur",
    area: "City Centre",
    lat: 29.3956,
    lng: 71.6991,
    phone: "+92-62-9255300",
    emergency: true,
    beds: 800,
    rating: 3.3,
    timings: "24/7",
    established: 1971,
    specialties: [
      { name: "General Surgery", rating: 3.4 },
      { name: "Gynecology", rating: 3.3 },
      { name: "Pediatrics", rating: 3.3 },
      { name: "Orthopedics", rating: 3.2 },
    ],
  },

  // ─── GUJRANWALA ───────────────────────────────────────────────────────────────
  {
    name: "DHQ Hospital Gujranwala",
    type: "public",
    city: "Gujranwala",
    province: "Punjab",
    address: "G.T. Road, Gujranwala",
    area: "G.T. Road",
    lat: 32.1811,
    lng: 74.1829,
    phone: "+92-55-9200351",
    emergency: true,
    beds: 800,
    rating: 3.2,
    timings: "24/7",
    established: 1965,
    specialties: [
      { name: "Emergency Medicine", rating: 3.3 },
      { name: "General Surgery", rating: 3.2 },
      { name: "Gynecology", rating: 3.2 },
      { name: "Orthopedics", rating: 3.1 },
      { name: "Pediatrics", rating: 3.2 },
    ],
  },
  {
    name: "Gujranwala Medical College Teaching Hospital",
    type: "public",
    city: "Gujranwala",
    province: "Punjab",
    address: "Opposite DHQ Hospital, Gujranwala",
    area: "G.T. Road",
    lat: 32.1821,
    lng: 74.1851,
    phone: "+92-55-3844080",
    emergency: true,
    beds: 600,
    rating: 3.4,
    timings: "24/7",
    established: 2001,
    specialties: [
      { name: "General Surgery", rating: 3.5 },
      { name: "Gynecology", rating: 3.4 },
      { name: "Cardiology", rating: 3.4 },
      { name: "Orthopedics", rating: 3.3 },
    ],
  },

  // ─── SIALKOT ──────────────────────────────────────────────────────────────────
  {
    name: "Allama Iqbal Memorial Hospital Sialkot",
    type: "public",
    city: "Sialkot",
    province: "Punjab",
    address: "Paris Road, Sialkot",
    area: "Paris Road",
    lat: 32.4921,
    lng: 74.5312,
    phone: "+92-52-9250110",
    emergency: true,
    beds: 600,
    rating: 3.3,
    timings: "24/7",
    established: 1968,
    specialties: [
      { name: "General Surgery", rating: 3.4 },
      { name: "Gynecology", rating: 3.3 },
      { name: "Orthopedics", rating: 3.2 },
      { name: "Pediatrics", rating: 3.3 },
    ],
  },
  {
    name: "Sialkot Medical Complex",
    type: "private",
    city: "Sialkot",
    province: "Punjab",
    address: "Cantt Area, Sialkot",
    area: "Cantt",
    lat: 32.5131,
    lng: 74.5401,
    phone: "+92-52-3564001",
    emergency: true,
    beds: 150,
    rating: 4.0,
    timings: "24/7",
    established: 2008,
    specialties: [
      { name: "Cardiology", rating: 4.1 },
      { name: "General Surgery", rating: 4.0 },
      { name: "Gynecology", rating: 4.0 },
      { name: "Orthopedics", rating: 3.9 },
    ],
  },

  // ─── ABBOTTABAD ───────────────────────────────────────────────────────────────
  {
    name: "Ayub Teaching Hospital Abbottabad",
    type: "public",
    city: "Abbottabad",
    province: "KPK",
    address: "Mansehra Road, Abbottabad",
    area: "Mansehra Road",
    lat: 34.1629,
    lng: 73.2218,
    phone: "+92-992-382681",
    emergency: true,
    beds: 900,
    rating: 3.5,
    timings: "24/7",
    established: 1981,
    specialties: [
      { name: "General Surgery", rating: 3.6 },
      { name: "Gynecology", rating: 3.5 },
      { name: "Orthopedics", rating: 3.5 },
      { name: "Cardiology", rating: 3.4 },
      { name: "Pediatrics", rating: 3.5 },
    ],
  },
  {
    name: "Abbottabad International Medical Complex",
    type: "private",
    city: "Abbottabad",
    province: "KPK",
    address: "Mansehra Road, Abbottabad",
    area: "Mansehra Road",
    lat: 34.1549,
    lng: 73.2168,
    phone: "+92-992-401000",
    emergency: true,
    beds: 200,
    rating: 4.1,
    timings: "24/7",
    established: 2009,
    specialties: [
      { name: "Cardiology", rating: 4.2 },
      { name: "General Surgery", rating: 4.1 },
      { name: "Gynecology", rating: 4.1 },
      { name: "Orthopedics", rating: 4.0 },
    ],
  },

  // ─── MARDAN ───────────────────────────────────────────────────────────────────
  {
    name: "Mardan Medical Complex",
    type: "public",
    city: "Mardan",
    province: "KPK",
    address: "Mardan Road, Mardan",
    area: "Mardan Road",
    lat: 34.2001,
    lng: 72.0481,
    phone: "+92-937-9230140",
    emergency: true,
    beds: 700,
    rating: 3.3,
    timings: "24/7",
    established: 2000,
    specialties: [
      { name: "General Surgery", rating: 3.4 },
      { name: "Gynecology", rating: 3.3 },
      { name: "Orthopedics", rating: 3.2 },
      { name: "Pediatrics", rating: 3.3 },
      { name: "Cardiology", rating: 3.2 },
    ],
  },

  // ─── SARGODHA ─────────────────────────────────────────────────────────────────
  {
    name: "DHQ Hospital Sargodha",
    type: "public",
    city: "Sargodha",
    province: "Punjab",
    address: "University Road, Sargodha",
    area: "University Road",
    lat: 32.0836,
    lng: 72.6748,
    phone: "+92-48-9230160",
    emergency: true,
    beds: 700,
    rating: 3.2,
    timings: "24/7",
    established: 1960,
    specialties: [
      { name: "General Surgery", rating: 3.3 },
      { name: "Gynecology", rating: 3.2 },
      { name: "Orthopedics", rating: 3.1 },
      { name: "Pediatrics", rating: 3.2 },
    ],
  },
  {
    name: "Sargodha Medical College Hospital",
    type: "public",
    city: "Sargodha",
    province: "Punjab",
    address: "Lyallpur Road, Sargodha",
    area: "Lyallpur Road",
    lat: 32.0901,
    lng: 72.6801,
    phone: "+92-48-3728200",
    emergency: true,
    beds: 500,
    rating: 3.4,
    timings: "24/7",
    established: 2005,
    specialties: [
      { name: "General Surgery", rating: 3.5 },
      { name: "Gynecology", rating: 3.4 },
      { name: "Cardiology", rating: 3.4 },
      { name: "Orthopedics", rating: 3.3 },
    ],
  },

  // ─── DERA GHAZI KHAN ──────────────────────────────────────────────────────────
  {
    name: "DHQ Hospital Dera Ghazi Khan",
    type: "public",
    city: "Dera Ghazi Khan",
    province: "Punjab",
    address: "Hospital Road, D.G. Khan",
    area: "Hospital Road",
    lat: 30.0511,
    lng: 70.6347,
    phone: "+92-64-9260121",
    emergency: true,
    beds: 600,
    rating: 3.0,
    timings: "24/7",
    established: 1972,
    specialties: [
      { name: "General Surgery", rating: 3.1 },
      { name: "Gynecology", rating: 3.0 },
      { name: "Pediatrics", rating: 3.0 },
      { name: "Internal Medicine", rating: 3.1 },
    ],
  },

  // ─── LARKANA ──────────────────────────────────────────────────────────────────
  {
    name: "Chandka Medical College Hospital",
    type: "public",
    city: "Larkana",
    province: "Sindh",
    address: "Chandka Medical College, Larkana",
    area: "Chandka",
    lat: 27.5585,
    lng: 68.2152,
    phone: "+92-74-9410246",
    emergency: true,
    beds: 900,
    rating: 3.1,
    timings: "24/7",
    established: 1973,
    specialties: [
      { name: "General Surgery", rating: 3.2 },
      { name: "Gynecology", rating: 3.1 },
      { name: "Pediatrics", rating: 3.1 },
      { name: "Internal Medicine", rating: 3.2 },
      { name: "Orthopedics", rating: 3.0 },
    ],
  },

  // ─── MIRPUR (AJK) ─────────────────────────────────────────────────────────────
  {
    name: "Divisional Headquarters Hospital Mirpur",
    type: "public",
    city: "Mirpur",
    province: "AJK",
    address: "Hospital Road, Mirpur",
    area: "Hospital Road",
    lat: 33.1477,
    lng: 73.7513,
    phone: "+92-5827-440206",
    emergency: true,
    beds: 400,
    rating: 3.2,
    timings: "24/7",
    established: 1975,
    specialties: [
      { name: "General Surgery", rating: 3.3 },
      { name: "Gynecology", rating: 3.2 },
      { name: "Pediatrics", rating: 3.2 },
      { name: "Internal Medicine", rating: 3.3 },
    ],
  },
  {
    name: "Shifa International Hospital Mirpur",
    type: "private",
    city: "Mirpur",
    province: "AJK",
    address: "New Mirpur City, Mirpur",
    area: "New Mirpur",
    lat: 33.1501,
    lng: 73.7581,
    phone: "+92-5827-420001",
    emergency: true,
    beds: 150,
    rating: 4.0,
    timings: "24/7",
    established: 2011,
    specialties: [
      { name: "Cardiology", rating: 4.1 },
      { name: "General Surgery", rating: 4.0 },
      { name: "Gynecology", rating: 4.0 },
      { name: "Orthopedics", rating: 3.9 },
    ],
  },

  // ─── MUZAFFARABAD (AJK) ───────────────────────────────────────────────────────
  {
    name: "Azad Kashmir Medical College Hospital",
    type: "public",
    city: "Muzaffarabad",
    province: "AJK",
    address: "Chattar Kali, Muzaffarabad",
    area: "Chattar Kali",
    lat: 34.3601,
    lng: 73.4712,
    phone: "+92-5822-922710",
    emergency: true,
    beds: 500,
    rating: 3.2,
    timings: "24/7",
    established: 1985,
    specialties: [
      { name: "General Surgery", rating: 3.3 },
      { name: "Gynecology", rating: 3.2 },
      { name: "Orthopedics", rating: 3.2 },
      { name: "Pediatrics", rating: 3.2 },
    ],
  },

  // ─── GILGIT-BALTISTAN ─────────────────────────────────────────────────────────
  {
    name: "District Headquarters Hospital Gilgit",
    type: "public",
    city: "Gilgit",
    province: "Gilgit-Baltistan",
    address: "Hospital Road, Gilgit",
    area: "Hospital Road",
    lat: 35.9221,
    lng: 74.3089,
    phone: "+92-5811-920130",
    emergency: true,
    beds: 300,
    rating: 3.0,
    timings: "24/7",
    established: 1960,
    specialties: [
      { name: "General Surgery", rating: 3.1 },
      { name: "Gynecology", rating: 3.0 },
      { name: "Pediatrics", rating: 3.0 },
      { name: "Internal Medicine", rating: 3.1 },
    ],
  },
  {
    name: "Aga Khan Health Services Hospital Gilgit",
    type: "private",
    city: "Gilgit",
    province: "Gilgit-Baltistan",
    address: "Jutial, Gilgit",
    area: "Jutial",
    lat: 35.9180,
    lng: 74.3201,
    phone: "+92-5811-452301",
    emergency: true,
    beds: 100,
    rating: 4.2,
    timings: "24/7",
    established: 2002,
    specialties: [
      { name: "General Surgery", rating: 4.3 },
      { name: "Gynecology", rating: 4.2 },
      { name: "Pediatrics", rating: 4.2 },
      { name: "Internal Medicine", rating: 4.1 },
    ],
  },
];

async function main() {
  await prisma.specialty.deleteMany();
  await prisma.hospital.deleteMany();

  console.log(`Seeding ${hospitals.length} hospitals across Pakistan…`);

  for (const h of hospitals) {
    await prisma.hospital.create({
      data: {
        name: h.name,
        type: h.type,
        city: h.city,
        province: h.province,
        address: h.address,
        area: h.area,
        lat: h.lat,
        lng: h.lng,
        phone: h.phone,
        emergency: h.emergency,
        beds: h.beds,
        rating: h.rating,
        timings: h.timings,
        established: h.established,
        specialties: {
          create: h.specialties,
        },
      },
    });
  }

  const count = await prisma.hospital.count();
  console.log(`✓ Seeded ${count} hospitals`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
